[package]

name = "regex-dfa"
version = "0.0.1"
authors = ["Geoffry Song <goffrie@gmail.com>"]

homepage = "https://github.com/goffrie/regex-dfa"
repository = "https://github.com/goffrie/regex-dfa"
documentation = "http://goffrie.github.io/regex-dfa"
license = "MIT"
keywords = ["regex", "dfa"]

[features]

unstable = []

[lib]

name = "regex_dfa"

[[bin]]

name = "regex_test"
doc = false

[dependencies]

vec_map = "0.3.0"
bit-set = "0.2.0"
